/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.java.myapp;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author chaiwat
 */
public class purify extends javax.swing.JFrame {

    /**
     * Creates new form purify
     */
    public purify() {
        initComponents();
        this.setTitle("โปรแกรมจัดการ Data เข้าสู่ระบบอัตโนมัต");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtUsername = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        lblUsername = new javax.swing.JLabel();
        lblPassword = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        btnCloseProgram = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CASCAP Purify V1.0.0");
        setFont(new java.awt.Font("Angsana New", 1, 24)); // NOI18N
        getContentPane().setLayout(null);
        getContentPane().add(txtUsername);
        txtUsername.setBounds(180, 60, 150, 40);
        getContentPane().add(txtPassword);
        txtPassword.setBounds(180, 100, 150, 40);

        lblUsername.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        lblUsername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblUsername.setText("Username:");
        getContentPane().add(lblUsername);
        lblUsername.setBounds(60, 50, 120, 40);

        lblPassword.setFont(new java.awt.Font("Angsana New", 1, 36)); // NOI18N
        lblPassword.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lblPassword.setText("Password:");
        getContentPane().add(lblPassword);
        lblPassword.setBounds(40, 100, 140, 30);

        btnLogin.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        btnLogin.setText("Login");
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        getContentPane().add(btnLogin);
        btnLogin.setBounds(100, 150, 210, 80);

        btnCloseProgram.setFont(new java.awt.Font("Angsana New", 1, 48)); // NOI18N
        btnCloseProgram.setText("Close");
        btnCloseProgram.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseProgramActionPerformed(evt);
            }
        });
        getContentPane().add(btnCloseProgram);
        btnCloseProgram.setBounds(100, 230, 210, 80);

        setSize(new java.awt.Dimension(419, 374));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
        // assign user and password 
        projectdatabase dbconfig = new projectdatabase();
        
        // check login
        String connectdbcheck="localhostroot";
        
        String userpassword="xpc1234x";
        try {
            Class.forName("com.mysql.jdbc.Driver");
            switch (connectdbcheck) {
                case "localhostwebmaster":
                    dbconfig.dbconfig("localhost","webmaster","xpctc2004x","buffete_center");        // auto assting username password;
                    break;
                case "localhostroot":
                    dbconfig.dbconfig("localhost","root","","buffete_center");        // auto assting username password;
                    break;
                case "servercascap":
                    dbconfig.dbconfig();        // auto assting username password;
                    //connect =  DriverManager.getConnection("jdbc:mysql://www.cascap.in.th/v04cascap" +
                    //            "?user=purify&password=purifybykie");
                    break;
            }
            connect =  DriverManager.getConnection("jdbc:mysql://"+dbconfig.dbhost+"/"+dbconfig.dbusedbname +
                        "?user="+dbconfig.dbusername+"&password="+dbconfig.dbpasswords);

            s = connect.createStatement();
            
            String strUsername = new String(this.txtUsername.getText());
            String strPassword = new String(this.txtPassword.getPassword());

            String sql = "SELECT puser.*,password(concat('2015','"+strPassword+"')) as passwordlogin FROM  puser where username='"+strUsername+"' ";

            ResultSet rec = s.executeQuery(sql);
            
            int row = 0;
            while((rec!=null) && (rec.next()))
            {	
                System.out.println(ASCII2Unicode(rec.getString("passwords")));
                System.out.println(strPassword);
                // กำหนดค่า password ตามการถอดรหัส
                switch (connectdbcheck) {
                    case "localhostwebmaster":
                        break;
                    case "localhostroot":
                        userpassword=strPassword;
                        break;
                    case "servercascap":
                        userpassword=strPassword;
                        break;
                }
                if ( userpassword.equals(rec.getString("passwords")) ){
                    System.out.println("Login success by "+strUsername);
                    System.out.println(ASCII2Unicode(rec.getString("name")));
                    
                    // Show project list
                    //myProjectList projectlist = new myProjectList();
                    //projectlist.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
                    //projectlist.setVisible(true);
                    
                    // get Username & Name from Class
                    tbpuser user = new tbpuser();
                    user.setupUser(rec.getString("pid"), rec.getString("name"), rec.getString("surname"));

                    // open project
                    project proj = new project();
                    //proj.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
                    proj.setVisible(true);
                    this.setVisible(false);
                }else{
                    //
                    System.out.println("Login ไม่สำเร็จ ");
            
                }
//                System.out.println(ASCII2Unicode(rec.getString("pid")));
//                System.out.println(ASCII2Unicode(rec.getString("name")));
//                System.out.println(ASCII2Unicode(rec.getString("surname")));
//                JOptionPane.showMessageDialog(this, "Login โดย " + ASCII2Unicode(rec.getString("name")) + ASCII2Unicode(rec.getString("surname")));
//                System.exit(0);
                row++;

                /*
                 *  model.addRow(new Object[]{
                    rec.getString("CustomerID")
                    ,rec.getString("Name"),rec.getString("Email")
                    ,rec.getString("CountryCode")
                    ,rec.getString("Budget")
                    ,rec.getString("Used")
                    });
                 */
            }
            
            rec.close();
            
            if( row == 0 ){
                System.out.println("ไม่พบ username ที่ใช้ "+strUsername);
            }

        } catch (ClassNotFoundException | SQLException e) {
            // TODO Auto-generated catch block
            JOptionPane.showMessageDialog(null, "error:"+e.getMessage());
            e.printStackTrace();
        }

        try {
            if(s != null) {
                s.close();
                connect.close();
            }
        } catch (SQLException e) {
            // TODO Auto-generated catch block
            e.printStackTrace();
        }
        // clear text
        this.txtPassword.setText("");
        this.txtUsername.setText("");
    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnCloseProgramActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseProgramActionPerformed
        // TODO add your handling code here:
        // New Form
        //myForm2 form2 = new myForm2();
        //form2.setDefaultCloseOperation(this.HIDE_ON_CLOSE);
        //form2.setVisible(true);

        //setVisible(false);
        int dialogButton = JOptionPane.YES_NO_OPTION;
        Font font = new Font("Angsana New", 1, 24);
        //UIManager um = new UIManager();
        UIManager.put("OptionPane.messageFont", font);
        UIManager.put("OptionPane.messageForeground", Color.red);
        UIManager.put("Panel.background", Color.yellow);
        JOptionPane.showConfirmDialog (null, "คุณต้องการปิดโปรแกรม หรือไม่ ?","Warning !",dialogButton);
        if(dialogButton == JOptionPane.YES_OPTION)
        { //The ISSUE is here
            System.exit(0);
        }
    }//GEN-LAST:event_btnCloseProgramActionPerformed

    public static String ASCII2Unicode(String ascii) {
        
        if( ascii==null ){
            return "[Null]";
        }else{
            StringBuilder unicode = new StringBuilder(ascii);
            
            int code;
            
            for(int i = 0; i < ascii.length(); i++) {
                
                code = (int)ascii.charAt(i);
                
                if ((0xA1 <= code) && (code <= 0xFB))
                    
                    unicode.setCharAt( i, (char)(code + 0xD60));
                
            }
            return unicode.toString();
        }

        

    }
    
    Connection connect = null;
    Statement s = null;
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(purify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(purify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(purify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(purify.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* assing and settup value view form before display form */
        
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new purify().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCloseProgram;
    private javax.swing.JButton btnLogin;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblUsername;
    private javax.swing.JPasswordField txtPassword;
    private javax.swing.JTextField txtUsername;
    // End of variables declaration//GEN-END:variables
}
